# Generated by Django 3.1.7 on 2021-03-11 08:53

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default=None, max_length=100, null=True)),
                ('avatar', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('subject', models.CharField(blank=True, default='Bill', max_length=500, null=True)),
                ('body', models.CharField(blank=True, default='Please find your bill attached to this mail.', max_length=1000, null=True)),
                ('smtp_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=50, null=True)),
                ('smtp_port', models.CharField(blank=True, default='587', max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default=None, max_length=100, null=True)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('date', models.DateTimeField(default=None, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=None, max_digits=13, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_item', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default=None, max_length=100, null=True)),
                ('name', models.CharField(default=None, max_length=255, null=True)),
                ('date', models.DateTimeField(default=None, null=True)),
                ('avatar', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(default=None, max_length=100, null=True)),
                ('date', models.DateTimeField(default=None, null=True)),
                ('customer_name', models.CharField(default=None, max_length=255, null=True)),
                ('customer_email', models.EmailField(blank=True, default=None, max_length=255, null=True)),
                ('remarks', models.JSONField()),
                ('documents', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('items_id', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, default=list, size=None)),
                ('amount', models.DecimalField(decimal_places=2, default=None, max_digits=100)),
                ('quantity', models.DecimalField(decimal_places=3, default=None, max_digits=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_bill', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
