# Generated by Django 3.1.7 on 2021-03-19 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20210312_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
